---
version: '2'
services:
  zookeeper:
    container_name: zookeeper
    build: zookeeper/
    environment:
      CONFLUENT_SECURITY_MASTER_KEY: +WnlKlf5LJMS5NU1je4k+Oeay+2lGt+dnJj69oOScdo=
    volumes:
      - ./etc/zookeeper:/etc/kafka

  kafka:
    container_name: kafka
    build: kafka/
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      CONFLUENT_SECURITY_MASTER_KEY: +WnlKlf5LJMS5NU1je4k+Oeay+2lGt+dnJj69oOScdo=
    volumes:
      - ./etc/kafka:/etc/kafka

  kafka-connect-cp:
    build: kafka-connect/
    container_name: kafka-connect
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 18083:18083
    volumes:
      - ./etc/connect:/etc/kafka-connect
    environment:
      CONFLUENT_SECURITY_MASTER_KEY: +WnlKlf5LJMS5NU1je4k+Oeay+2lGt+dnJj69oOScdo=
      CONNECT_BOOTSTRAP_SERVERS: "kafka:29092"
      CONNECT_REST_PORT: 18083
      CONNECT_GROUP_ID: kafka-connect-cp
      CONNECT_CONFIG_STORAGE_TOPIC: docker-kafka-connect-cp-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-kafka-connect-cp-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-kafka-connect-cp-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect-cp"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: '/usr/share/java'
      CONNECT_LISTENERS: 'http://0.0.0.0:18083'
